services:
  db:
    image: postgres:17
    container_name: postgres17_compose
    restart: always
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: test1234
      POSTGRES_DB: demo_development
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      
volumes:
  db_data:
